before_install:
    - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
    - sudo apt-get update -o Dir::Etc::sourcelist="sources.list.d/terry_guo-gcc-arm-embedded-precise.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
install:
    - sudo apt-get install gcc-arm-none-eabi
    - curl --retry 3 --output rust.tgz
        http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
    - tar xf rust.tgz
    - (cd ./rust-nightly-x86_64-unknown-linux-gnu/; sudo ./install.sh)
    - export LD_LIBRARY_PATH=/usr/local/lib
    - (mkdir -p ./thirdparty/rust)
    - "(cd ./thirdparty/rust; wget -O rust.tar.gz https://github.com/rust-lang/rust/tarball/`rustc --version|awk '{sub(/\\(/, \"\", $3); print $3}'`; tar -zx --strip-components=1 -f rust.tar.gz)"
before_script:
    - rustc --version
script:
    - rake build_all test
env:
  matrix:
    - PLATFORM=lpc17xx
    - PLATFORM=stm32f4
    - PLATFORM=stm32l1
    - PLATFORM=k20
