# Site settings
title: zinc.rs
email: farcaller@gmail.com
description: "The bare metal stack for rust"
baseurl: ""
url: "http://zinc.rs"
exclude:
 - Gemfile
 - Gemfile.lock

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
